bapsflib/_hdf_mappers/__init__.py
bapsflib/_hdf_mappers/msi/__init__.py
bapsflib/_hdf_mappers/msi/discharge.py
bapsflib/_hdf_mappers/msi/gaspressure.py
bapsflib/_hdf_mappers/msi/heater.py
bapsflib/_hdf_mappers/msi/interferometerarray.py
bapsflib/_hdf_mappers/msi/magneticfield.py
bapsflib/_hdf_mappers/msi/map_msi.py
bapsflib/_hdf_mappers/msi/templates.py
bapsflib/_hdf_mappers/msi/tests/common.py
bapsflib/_hdf_mappers/msi/tests/test_discharge.py
bapsflib/_hdf_mappers/msi/tests/test_gaspressure.py
bapsflib/_hdf_mappers/msi/tests/test_heater.py
bapsflib/_hdf_mappers/msi/tests/test_interferometerarray.py
bapsflib/_hdf_mappers/msi/tests/test_magneticfield.py
bapsflib/_hdf_mappers/msi/tests/test_map_msi.py
bapsflib/lapd/_hdf/hdfmapper.py
bapsflib/lapd/_hdf/hdfreadmsi.py
docs/src/bapsflib._hdf_mappers.msi.discharge.rst
docs/src/bapsflib._hdf_mappers.msi.gaspressure.rst
docs/src/bapsflib._hdf_mappers.msi.heater.rst
docs/src/bapsflib._hdf_mappers.msi.interferometerarray.rst
docs/src/bapsflib._hdf_mappers.msi.magneticfield.rst
docs/src/bapsflib._hdf_mappers.msi.map_msi.rst
docs/src/bapsflib._hdf_mappers.msi.rst
docs/src/bapsflib._hdf_mappers.msi.templates.rst

All MSI mapping classes and modules are updated such that:
1. All mapping classes satisfy PEP8 CamelCase
1. All mapping classes have typing annotations
1. documentations source files (in '/docs/src/') have autosummary headers

Update MSI mapping classes to satisfy pep8

---

bapsflib/_hdf/maps/controls/__init__.py
bapsflib/_hdf/maps/controls/map_controls.py
bapsflib/_hdf/maps/controls/n5700ps.py
bapsflib/_hdf/maps/controls/nixz.py
bapsflib/_hdf/maps/controls/tests/__init__.py
bapsflib/_hdf/maps/controls/tests/common.py
bapsflib/_hdf/maps/controls/tests/fauxnixz.py
bapsflib/_hdf/maps/controls/tests/fauxsixk.py
bapsflib/_hdf/maps/controls/tests/test_nixz.py
bapsflib/_hdf/maps/tests/fauxhdfbuilder.py
bapsflib/_hdf/utils/hdfreadcontrol.py
bapsflib/_hdf/utils/tests/__init__.py
bapsflib/_hdf/utils/tests/test_hdfoverview.py
bapsflib/_hdf/utils/tests/test_hdfreadcontrol.py

Adds ability to interface with the 'NI_XZ' control device.  The 'NI_XZ' control device is used to moving a probe in the XZ-plane of the LaPD.
This merge includes:
1.  Addition of the `HDFMapControlNIXZ` class for mapping the 'NI_XZ' control device
* 100% coverage of tests
1. `HDFReadControl` needed to be updated such that the population of the`'xyz'` field does not fail, since the 'NI_XZ' dataset does not store y-coordinate values
* Now, when defining the `configs` mapping dictionary, if the dataset field is defined as a null string `''`, then `HDFReadControl` assumes that the corresponding numpy field is supposed to be filled with zeros.
* For example, if
```
configs[cname]['state values']['xyz'] = {
'dset paths': 'path/to/dataset',
'dset field': ('x', '', 'z'),
'shape': (3,),
'dtype': …
```

'NI_XZ' control mapping module

---

README.md
appveyor.yml
bapsflib/_hdf/maps/tests/fauxhdfbuilder.py
bapsflib/_hdf/utils/tests/__init__.py
bapsflib/_hdf/utils/tests/test_file.py
bapsflib/_hdf/utils/tests/test_hdfoverview.py
bapsflib/_hdf/utils/tests/test_hdfreadcontrol.py
bapsflib/_hdf/utils/tests/test_hdfreaddata.py
bapsflib/_hdf/utils/tests/test_hdfreadmsi.py
bapsflib/_hdf/utils/tests/test_helpers.py
bapsflib/lapd/_hdf/tests/__init__.py
bapsflib/lapd/_hdf/tests/test_file.py
bapsflib/lapd/_hdf/tests/test_lapdmap.py
bapsflib/lapd/_hdf/tests/test_lapdoverview.py

What was done:
1. created `appveyor.yml` for AppVeyor support
* for running tests on Windows platform
* tests are run on python 3.5, 3.6, and 3.7 environments
1. improved context managing of opening/closing of files `bapsflib._hdf.utils.file.File` and `bapsflib.lapd._hdf.file.File`
* this is done by creating the decorators `with_bf` and `with_lapdf` and implementing them in all appropriate tests
* by proper context managing, the temporary HDF5 file can be properly removed/deleted when tests are complete

Add AppVeyor Support for Windows

---

bapsflib/_hdf/maps/digitizers/sis3301.py
bapsflib/_hdf/maps/digitizers/tests/test_sis3301.py

Addresses two 'SIS 3301' mapping variations seen in SmPD HDF5 files:
1. the shot number field in header dataset files can be named `'Shot'` (original scheme) or `'Shot number'` (seen in SmPD HDF5 files) [issue GH-28]
1. the configuration group attribute `'Samples to average'` (original scheme) can be named `'Unnamed'` (seen in SmPD HDF5 files) instead [issue GH-29]
Closes #28 and #29

Updated 'SIS 3301' digitizer mapping for variations seen in SmPD HDF5 files

---

bapsflib/_hdf/utils/helpers.py
bapsflib/_hdf/utils/tests/test_helpers.py

Update function `condition_shotnum()` so single element `numpy` arrays do not raise a `ValueError` (see issue #35 for details)
closes #35

Allow `condition_shotnum()` to handle single element numpy arrays

---

.coveragerc
README.md
bapsflib/__init__.py
bapsflib/_hdf/__init__.py
bapsflib/_hdf/maps/__init__.py
bapsflib/_hdf/maps/digitizers/__init__.py
bapsflib/_hdf/maps/msi/__init__.py
bapsflib/_hdf/utils/__init__.py
bapsflib/_hdf/utils/tests/__init__.py
bapsflib/lapd/__init__.py
bapsflib/lapd/_hdf/__init__.py
bapsflib/lapd/_hdf/tests/__init__.py
bapsflib/lapd/_hdf/tests/test_file.py
bapsflib/lapd/constants/__init__.py
bapsflib/lapd/tools/__init__.py
bapsflib/lapd/tools/tools.py
bapsflib/plasma/__init__.py
bapsflib/plasma/core.py
bapsflib/utils/__init__.py
bapsflib/utils/decorators.py
bapsflib/utils/tests/test_decorators.py
docs/changelog.rst
docs/src/bapsflib.plasma.rst
docs/src/bapsflib.rst
docs/src/bapsflib.utils.decorators.rst
docs/src/bapsflib.utils.rst

Merge in last remaining misc features to get to v1.0.1:
* update version string to `'1.0.1'`
* move `__all__` above imports (PEP8 - module level dunders follow docstrings)
* update `changelog.rst`
* move docorators `with_bf` and `with_lapdf` out of test packages and into module `bapsflib.utils.decorators`
* decorators are generalized to work on functions and methods
* file opening settings can be defined through (in priority) (1) function arguments, (2) appropriately named attributes on method's `self` argument, and (3) decorator keywords
* tests created to cover `with_bf` and `with_lapdf`
* source documentation page made for `bapsflib.utils.decorators`

Merge v1.0.1

---

.pep8speaks.yml
docs/conf.py
pyproject.toml
requirements.txt
requirements/build.txt
requirements/docs.txt
requirements/extras.txt
requirements/install.txt
requirements/tests.txt
setup.cfg
setup.py

1. Moves package metadata out of `setup.py` and into `setup.cfg`.
1. Creates `pyproject.toml`.
1. Consolidates requirements files and establish relations with the `extras_requires` defined in `setup.cfg`.
- Create directory `./requirements/*.txt` where each `*.txt` mimics the requirements defined by `extras_requires` in `setup.cfg`.
- Comments in both locations are added to establish "link-backs".
- The `./requirements.txt` specifies all packages defined by the files in `./requirements/`.

Move metadata to setup.cfg and consolidate requirements

---

.readthedocs.yml

This adds the `.readthedocs.yml` configuration file for controlling Read the Docs builds.

Add YML configuration file for RTD

---

.travis.yml
appveyor.yml
bapsflib/__init__.py
pyproject.toml
requirements/build.txt
requirements/install.txt
setup.cfg
setup.py

Set package `__version__` using `setuptools_scm`, which leverages git scm (source-control management).
1. `__version__` is defined similarly to that in https://github.com/PlasmaPy/PlasmaPy/pull/774
1. In `setup.py` let `setup()` define version with `use_scm_version=True`.
1. Update `.travis.yml` to run tests on python 3.6-3.8 (on Linus).
1. Update `appveyor.yml` to run test on python 3.6-3.8 (for windows)

Set package version using setuptools_scm

---

pyproject.toml

This PR setups up the [gilesbot](https://github.com/Cadair/giles) to check for proper `towncrier` change log entries.
According to https://github.com/PlasmaPy/PlasmaPy/pull/719#issuecomment-549155899, the actual check will not appear until it is in the master branch.

Setup gilesbot for Change Log checks

---

bapsflib/_hdf/utils/helpers.py
bapsflib/_hdf/utils/tests/test_hdfreaddata.py
changelog/65.feature.rst

`h5py >= 3.0` has changed the order of it's indexing for datasets to be the reverse of what was in `h5py < 3.0`.  For example, ...
```python
first, last =dataset[[-1, 0], "column name"]
first, last =dataset[[0, -1], "column name"]
```
To make `bapsflib`'s functionality more robust, the following approach is taken...
```python
first = dataset[0, "column name"]
last = dataset[-1, "column name"]
```

Improve indexing in anticipation of allowing h5py >= 3.0

---

.git-blame-ignore-revs
changelog/68.trivial.rst

Add `.git-blame-ignore-revs` so `git blame` will ignore mass refactoring from `isort` (PR #66 e8e6bc1e62829aeaac859a9691890fb4c582dbdf) and `black` (PR #67 2906fd682e0f9dd905fc5b7121c0fbf2caba7734).
This will make `git blame` look past the two major refactoring commits to get the last relevant `git commit` comment.
More details can be read at...
https://github.com/psf/black/blob/d3cc63316b10c3ddc0e6a97a71130f30598ba5ef/README.md#migrating-your-code-style-without-ruining-git-blame
https://www.moxio.com/blog/43/ignoring-bulk-change-commits-with-git-blame

Add `.git-blame-ignore-revs`

---

.github/workflows/linters.yml
bapsflib/_hdf/maps/digitizers/siscrate.py
bapsflib/_hdf/maps/digitizers/tests/test_siscrate.py
bapsflib/_hdf/utils/tests/test_hdfreaddata.py
bapsflib/plasma/core.py
requirements/extras.txt
setup.cfg

Set requirement `black==22.3.0`...
- Eliminates the linter CI failures due to the release of `click==8.1`
- Refactor code to `black==22.3.0` standards

Set requirement `black==22.3.0`

---

requirements/install.txt
setup.cfg

`numpy.asscalar` was deprecated in `numpy` `v1.16` and officially removed in `v1.23`.  However, `bapsflib` currently depends on older versions of `astropy` that use `numpy.asscalar`.

Set upper limit for numpy to `< 1.23`

---

.github/workflows/linters.yml
bapsflib/_hdf/maps/controls/parsers.py
bapsflib/_hdf/maps/digitizers/tests/fauxsiscrate.py
bapsflib/_hdf/maps/digitizers/tests/test_siscrate.py
bapsflib/_hdf/maps/msi/tests/common.py
bapsflib/_hdf/utils/hdfreadcontrols.py
bapsflib/_hdf/utils/tests/test_helpers.py
bapsflib/lapd/_hdf/tests/test_lapdmap.py
bapsflib/lapd/constants/constants.py
changelog/86.pkg_management.rst
changelog/86.trivial.rst
docs/changelog/1.0.1.rst
docs/installation.rst
requirements.txt
requirements/docs.txt
requirements/extras.txt
setup.cfg

This PR does:
1. Adds `codespell` as an extras package dependency.
2. Defines `codespell`'s configuration in the `setup.cfg`.
3. Adds a `codespell` check to the `linters.yml` GA workflow.
4. Corrects miss spellings identified by `codespell`.

Add to `linters` GA workflow `codespell`

---

.readthedocs.yml
requirements/docs.txt
setup.cfg

See the following RTD notice
https://blog.readthedocs.com/drop-support-system-packages/

Update `readthedocs.yml` to remove deprecated settings

---

.github/workflows/tests.yml
changelog/126.pkg_management.rst
requirements/install.txt
setup.cfg

For now, restring dependency to `numpy >= 1.20, < 2.0`.

Restrict `numpy` dependency to `< 2`

---

.github/workflows/tests.yml
codecov.yml

Update codecov step in github action to be consistent with `@v4` format.

Update codecov ci

---

.github/workflows/check_pr_changelog.yml

I moved the bot upstream to Scientific Python. It is unfortunate that you have to fork it and use it like this. We would welcome a PR to https://github.com/scientific-python/action-towncrier-changelog if you ever wishes to contribute upstream. Thanks!
xref https://github.com/scientific-python/action-towncrier-changelog/issues/4

MNT: Change log bot has moved to Scientific Python

---

bapsflib/_hdf/maps/controls/parsers.py
bapsflib/_hdf/maps/controls/tests/test_parsers.py
bapsflib/_hdf/maps/controls/tests/test_templates.py
bapsflib/_hdf/utils/tests/test_hdfreadcontrol.py
bapsflib/_hdf/utils/tests/test_hdfreaddata.py
changelog/136.pkg_management.rst
requirements/install.txt
setup.cfg

Remove dependency restriction `numpy < 2.0`
To accomplish this the following was done:
* replaced `np.unicode_` with `np.str_`
* Updated `TestHDFReadData.assetDataArrayValues` to use `np.allclose()` instead of `np.array_equal`.  The latter was running into floating point rounding issues causing erroneous test failures.

Remove dependency restriction `numpy < 2.0`

---

changelog/139.doc.rst
docs/conf.py
requirements/docs.txt
setup.cfg

Setup the Sphinx extension [`sphinx-hoverxref`](https://sphinx-hoverxref.readthedocs.io/en/latest/)

Setup `sphinx-hoverxref`

---

.github/workflows/linters.yml

This PR updates the `linters.yml` workflow, specifically the `isort-action` workflow.  `isort` started installing dependencies into their own virtual environment (https://github.com/isort/isort-action/pull/96), which prevent our `Install isort` step from properly setting up dependencies.

Patch `isort-action` workflow

---

bapsflib/_hdf/maps/controls/tests/common.py
bapsflib/_hdf/maps/controls/tests/test_n5700ps.py
bapsflib/_hdf/maps/controls/tests/test_nixyz.py
bapsflib/_hdf/maps/controls/tests/test_nixz.py
bapsflib/_hdf/maps/controls/tests/test_sixk.py
bapsflib/_hdf/maps/controls/tests/test_waveform.py

This PR updates several tests to reflect changes made in PR #141.
- Add a test method `ControlTestCase.test_contype`.  This ensures the `contype` class attribute is properly tested if the specific control device tests inherit from `ControlTestCase`.
- Redundant methods or removed from specific control device tests.
- `ControlTestCase.assertConrolMapBasics()` is updated to allow `config['shotnum']['dset paths']` to be `None`.
- `ControlTestCase.assertSVConfig()` is updated to allow (and ensure) `config['state values'][<key>]['dset paths']` is a subset of `config['dset paths']`.

Update tests for control device mappings.

---

bapsflib/_hdf/utils/hdfreadcontrols.py
bapsflib/_hdf/utils/hdfreaddata.py
bapsflib/_hdf/utils/helpers.py
bapsflib/_hdf/utils/tests/test_hdfreadcontrol.py
bapsflib/_hdf/utils/tests/test_hdfreaddata.py
bapsflib/_hdf/utils/tests/test_helpers.py
changelog/156.trivial.1.rst
changelog/156.trivial.2.rst
changelog/156.trivial.3.rst

This PR overhauls functionality in `bapsflib._hdf.utils.helpers.py` to make it more flexible to the various ways control devices can save their data.
- `build_shotnum_dset_relation()`
- signature is changed so arguments are now `shotnum`, `dset`, `shotnumkey`, `n_configs`, `config_id`, and `config_column`
- new signature allows for specifying the dataset `dset` column (`config_column`) for with the `config_id` will be searched for
- `build_sndr_for_simple_dset()`
- only docstrings are updated
- `build_sndr_for_complex_dset()`
- signature is to match that of `build_shotnum_dset_relation()`
- `condition_controls()`
- only docstrings are updated
- `condition_shotnum()`
- signature is changed to accept arguments `shotnum`, `dest_list`, and `shotnumkey_list`
- `dset_list` and `shotnumkey_list` …

Overhaul functionality in `bapsflib._hdf.utils.helpers.py`

---

bapsflib/_hdf/utils/file.py
bapsflib/_hdf/utils/tests/test_file.py
changelog/158.feature.rst

Add method `get_digitizer_specs()` to the `File` class to more easily retrieve specs of the deployed digitizer.  This is a convenience method so users do NOT have to read data or navigate through the digitizer mapping objects to retrieve the desired digitizer specifications.

Add method `File.get_digitizer_specs()`
